### ISSUE TITLE
rename SUMMARY.md to SUMMARY.adoc

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp-book#14]
@LANTZT could you rename SUMMARY.md to its adoc version ?

**Comment by LANTZT** [comment]
@prudhomm Done, it will be up into the next merge..

**Comment by prudhomm** [comment]
@LANTZT could you work with @MarieHouillon on the tutorial ?

**Comment by LANTZT** [comment]
@prudhomm Sure.

**Comment by prudhomm** [comment]
The first step is to add various issues about the tutorial and find a way to comment code in a better manner. 
there is a plugin include-codeblock which seems interesting. It uses line numbers (it would be best to use markers but...) https://plugins.gitbook.com/plugin/include-codeblock
