### ISSUE TITLE
Document the new mesh partitioning application

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp-book#7]
feelpp_mesh_partitioner should be documented in Feel++ Book

we could start an Application Section which reflects the applications subdirectory in Feel++
- Applications
  - Mesh 
    - Partitioning
  - Info
  - Models
    - CFD
  - CSM
  - FSI

/cc @vincentchabannes

**Comment by prudhomm** [comment]
any news on this @LANTZT? 
/cc @vincentchabannes

**Comment by LANTZT** [comment]
@prudhomm For this one, I didn't explore feelpp_mesh_partitioner yet .
I think I will start it properly when model definitions (#6)  will be completed.

**Comment by prudhomm** [comment]
@vincentchabannes the mesh partitioner app is now documented. I think it is good enough for now
