### ISSUE TITLE
use asciidoc format and not markdown format 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp-book#8]
Asciidoc has more features than markdown

provide a :toc: at beginning of files with several sections

**Comment by LANTZT** [comment]
@prudhomm Currently, I don't have a direct modification right on feelpp-book like other ones.
Can I have it, or do you prefer I work on a fork ?

**Comment by prudhomm** [comment]
actually I would prefer a fork first and see how it goes

**Comment by prudhomm** [comment]
I nevertheless gave the write auth for you but we should work with pull-request

**Comment by LANTZT** [comment]
Ok thanks, I will then add the fork to my Gitbook Editor
